name: release

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/checkout@master

    - name: Set up Python '3.10' x64
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
        architecture: x64

    - name: Build binary wheel
      run: python setup.py bdist_wheel

    - name: Create source dist
      run: python setup.py sdist

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1