name: Static Analysis
on: [push]

jobs:
  test:
    name: Bandit Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set Up Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade bandit

      - name: Execute Test
        run: bandit -r mabel

  semgrep:
    runs-on: ubuntu-latest
    name: SemGrep
    steps:
      - uses: actions/checkout@v3
      - name: Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/r2c
